package com.example.domain.model.poi.response

data class PoiItem(
    var id: String = "",
    var pkey: String = "",
    var navSeq: String = "",
    var collectionType: String = "",
    var name: String = "",
    var telNo: String = "",
    var frontLat: String = "",
    var frontLon: String = "",
    var noorLat: String = "",
    var noorLon: String = "",
    var upperAddrName: String = "",
    var middleAddrName: String = "",
    var lowerAddrName: String = "",
    var detailAddrName: String? = null,
    var mlClass: String = "",
    var firstNo: String = "",
    var secondNo: String? = null,
    var roadName: String = "",
    var firstBuildNo: String = "",
    var secondBuildNo: String? = null,
    var radius: String = "",
    var bizName: String? = null,
    var upperBizName: String = "",
    var middleBizName: String = "",
    var lowerBizName: String = "",
    var detailBizName: String = "",
    var rpFlag: String = "",
    var parkFlag: String = "",
    var detailInfoFlag: String = "",
    var desc: String? = null,
    var dataKind: String = "",
    var zipCode: String = "",
    var adminDongCode: String = "",
    var legalDongCode: String = "",
    var newAddressList: NewAddress = NewAddress(),
)
